# Generated by Django 4.1.7 on 2023-04-12 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_gasto_delete_animal_delete_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='articulo',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
